### PR TITLE
Update this plugin with following features

### PR DESCRIPTION
**Pull request by gmanojbabu**
- Native ext to install ktlint
- Abstracted ktlint command to ext
- Filter issues based on git diff
- lint all files or selected directory
- Pass custom ruleset
- Limit number of issues to be reported
- Custom binary path if required

### CODE REVIEW

**Comment by mataku** [comment]
Thanks, @gmanojbabu!
I will merge after checking your code. 

By the way, would you like to be an owner? If so, I will transfer gem ownership and this repo to you because I will not maintain this gem.

**Comment by gmanojbabu** [comment]
@mataku  You can transfer ownership, I can maintain this gem.

**Comment by mataku** [comment]
@gmanojbabu 
You saved my library! 

I will transfer this repository and gem ownership in this weekend. I will contact you when I've finished.

**Comment by gmanojbabu** [comment]
@mataku  Can you please review this PR?

**Comment by mataku** [comment]
👍

**Comment by mataku** [comment]
@gmanojbabu 
I added you as an owner of this gem. You can check at https://rubygems.org/gems/danger-ktlint

I will transfer this repo to you after you remove forked repo.

**Comment by gmanojbabu** [comment]
@mataku  Thank you for merging my PR.
I have deleted forked repo.

**Comment by mataku** [comment]
@gmanojbabu I've requested to transfer this repo!

**Pull request merged**
